### ISSUE TITLE
User Story: Providing an anonymous comment on the poll.

### ISSUE THREAD

**Issue by helenmurugan** [helenmurugan/love-running#1]
As a **runner**, I can **add a comment to the poll** so that **the site administrators receive my anonymous feedback**

# Acceptance Criteria
Acceptance Criteria 1: The option should be provided as a checkbox
Acceptance Criteria 2: The checkbox should be “checked” by default
Acceptance Criteria 3: The option should appear next to the submit button
Acceptance Criteria 4: After submitting the default submission confirmation should be adjusted to include the user name

# Tasks
- [ ] Task 1: Create html and css for the checkbox and submit button
- [ ] Task 2: Add default setting as checked
- [ ] Task 3: Add username to default submission confirmation

**Comment by helenmurugan** [comment]
Acceptance Criteria 1: The option should be provided as a checkbox
Accepotance Criteria 2: The checkbox should be “checked” by default
Acceptance Criteria 3: The option should appear next to the submit button
Acceptance Criteria 4: After submitting the default submission confirmation should be adjusted to include the user name
